kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: dexter
  name: dexants-httpd-vol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.10.4
    path: "/nfs/dexants_org"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dexter
  name: dexants-httpd-vol
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
